version: "3.8"
services:
  php-apache-environment:
    container_name: team-php-apache
    build:
      context: ./phpDir
      dockerfile: Dockerfile
    depends_on:
      - teamdb
    volumes:
      - ./phpDir/src:/var/www/html/
    ports:
      - 8001:80
  teamdb:
    container_name: teamdb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionPass
      MYSQL_DATABASE: lionDB
      MYSQL_USER: lionUser
      MYSQL_PASSWORD: lionPass
    ports:
      - "3307:3306"
    volumes:
      - ./:/docker-entrypoint-initdb.d
  teamphpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9081:80"
    restart: always
    environment:
      PMA_HOST: teamdb
    depends_on:
      - teamdb
